[package]
name = "ferro_spreadsheet"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A simple spreadsheet implementation in Rust"

[[bin]]
name = "sheet"
path = "sheet/src/main.rs"

[dependencies]
